# Generated by Django 5.1 on 2024-12-19 12:55

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_options_alter_tagpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagpost',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='tag', unique=True, verbose_name='Слаг'),
        ),
    ]
