# Generated by Django 5.1 on 2025-01-23 07:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_note_content_note_content_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_short',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=600, null=True, verbose_name='Краткий текст статьи'),
        ),
    ]
