# Generated by Django 5.1 on 2025-01-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_content_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Метаописание'),
        ),
    ]
